refactor: add drillInstallationDir to the agent parameters
Drill4J/lib-jvm-shared pull request #22
Opened 2023-10-06 10:06 UTC by iryabov

EPMDJ-10670

2023-10-09 13:05 UTC, RomanDavlyatshin requested changes

2023-10-09 14:14 UTC, iryabov commented on agent/src/mingwX64Main/kotlin/com/epam/drill/agent/configuration/DrillInstallationDir.kt
>  }
Fixed

2023-10-09 14:14 UTC, iryabov commented on agent/src/posixMain/kotlin/com/epam/drill/agent/configuration/DrillInstallationDir.kt
>  }
Fixed

2023-10-09 14:14 UTC, iryabov commented on agent/src/mingwX64Main/kotlin/com/epam/drill/agent/configuration/DrillInstallationDir.kt
> +    val isContainsAgentPath: (String?) -> Boolean = { it?.contains("-agentpath:") ?: false }
Fixed

2023-10-10 14:18 UTC, RomanDavlyatshin approved these changes

2023-10-11 14:32 UTC, merged